
resources:
  - name: connecting_resource_node_test
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

pipelines:
  - name: node_test
    steps:
      - name: u16
        type: Bash
        configuration:
          nodePool: u16
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images
      - name: u18
        type: Bash
        configuration:
          nodePool: u18
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images
            
      - name: u20
        type: Bash
        configuration:
          nodePool: u20
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images            

      - name: centos7
        type: Bash
        configuration:
          nodePool: centos7
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images


      - name: centos8
        type: Bash
        configuration:
          nodePool: centos8
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images

      - name: rhel7
        type: Bash
        configuration:
          nodePool: rhel7
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images


      - name: rhel8
        type: Bash
        configuration:
          nodePool: rhel8
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images
            
      - name: win_2019
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - write-output "Hi"
            - docker images
